spring:
  cloud:
    nacos:
      config:
        file-extension: yml
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:user-service.yml
      #- optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}  # 监听 DEFAULT_GROUP:user-service.yml
