server:
  port: 8082  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    active: dev
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
    url: jdbc:mysql://127.0.0.1:3306/learnhub?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.learnhub.common.mybatis.AutoGenericEnumTypeHandler
learnhub:
  auth:
    resource:
      enable: true
      excludeLoginPaths:
       #- /user/queryLoginUser/{isStaff}



